#Workflow name
name: CI/CD pipeline
on:
  #Manually trigger workflow run
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  #test jobs
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with: 
        java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Test
        run: mvn -B test
